CMD = time

# UDP server and client commands
us:
	python3 UDP/main_udp_server.py
uc:
	python3 UDP/main_udp_client.py


# TCP server and client commands
ts:
	python3 TCP/main_tcp_server.py
tc:
	python3 TCP/main_tcp_client.py

# wget https://github.com/sharkdp/hyperfine/releases/download/v1.16.1/hyperfine_1.16.1_amd64.deb
# sudo dpkg -i hyperfine_1.16.1_amd64.deb
